### ISSUE TITLE
wait_for can't resolve 400 series errors

### ISSUE THREAD

**Issue by plribeiro3000** [fog/fog-core#129]
This issue was moved from fog/fog#2910.

Take a look at the original issue for further details.

cc/ @geemus Feel free to add more context here if you think we need. I'm not totally into it yet.

**Comment by geemus** [comment]
Sure, basically I believe wait_for will loop (and ignore errors). It ignores errors because it is often used to deal with eventual consistency. ie if I look up a new record it may error because it doesn't appear to exist yet, but once things catch up, it should. That being said, if the error returned is 4XX, it means that the CLIENT is doing something wrong and no amount of blind retrying should be expected to make any difference (so it is a waste of time and erroring early is likely much more helpful/appropriate).

**Comment by plribeiro3000** [comment]
:+1:

**Comment by cphrmky** [comment]
> That being said, if the error returned is 4XX, it means that the CLIENT is doing something wrong

I would agree with you most of the time, but I don't accept this point without caveat.

For example with SoftLayer, when you order bare metal, you get an identifier for the machine as soon as you've called `@sl.servers.create(opts)`, the response is instant.  

However, the API is eventually consistent, and they do in fact throw out `404` responses when you try to GET that resource with the ID they gave you, until the transaction has cleared their billing system and the provisioning has begun.

**Comment by geemus** [comment]
Ah, good point. 404 should retry, but not many other 4XX things. Maybe we should start with JUST the auth ones, since they seem safe bets.

**Comment by geemus** [comment]
Willing to support, if needed, but doesn't look like there is much interest at present.
