### ISSUE TITLE
Too many opened files

### ISSUE THREAD

**Issue by PikachuEXE** [fog/fog-core#213]
Redirected from https://github.com/AssetSync/asset_sync/issues/348

In short the code at
https://github.com/AssetSync/asset_sync/blob/v2.1.0/lib/asset_sync/storage.rb#L125
Just open the file without closing it which is causing the issue

What else can be used for the `body` option in order to prevent too many opened file?

I think it's using `File.open` due to the example here:
http://fog.io/storage/

**Comment by icco** [comment]
Could you do File.read? Or assign file.open to something, pass that in, and then close after the fog call.

**Comment by geemus** [comment]
I think `File.open` would be preferable to `File.read`, as then it can read just one chunk at a time (instead of potentially reading many GB into memory). As the opens happen in assetsync and upload is asynchronous, I think the best bet would be assign the file handle to a variable and call close on it after the upload completes. That should get you what you need I think, but do let us know if you have other questions or concerns.

**Comment by PikachuEXE** [comment]
It might be also good to update the example?
Or add some tips after it

**Comment by geemus** [comment]
Certainly, would you be willing to help us flesh that out and clarify? Thanks!

**Comment by PikachuEXE** [comment]
I am not quite sure where to submit changes to that web page...

**Comment by geemus** [comment]
@PikachuEXE fair enough. Maybe just submit an issue on the assetsync repo and refer to this discussion?
