### ISSUE TITLE
fog-core 2+ behavior change 

### ISSUE THREAD

**Issue by gildub** [fog/fog-core#244]
This is happening in line:
https://github.com/fog/fog-openstack/blob/master/spec/network_spec.rb#L56

fog-core 1.45.0:
Existing behavior in line:
https://github.com/fog/fog-core/blob/v1.45.0/lib/fog/core/model.rb#L56
Where new_attributes returns:

```ruby
 :router_external=>false,
 "availability_zone_hints"=>[],
 "availability_zones"=>[],
 "description"=>"",
 :provider_physical_network=>nil,
 :subnets=>[],
 :shared=>false,
 :name=>"foo-net23",
 "created_at"=>"2016-05-11T12:05:18",
 "tags"=>[],
 "ipv6_address_scope"=>nil,
 :provider_network_type=>"vxlan",
 "updated_at"=>"2016-05-11T12:05:18",
 :tenant_id=>"dc4b3b173ee8467e9e2ae99e5c321d0c",
 :admin_state_up=>true,
 "ipv4_address_scope"=>nil,
 "port_security_enabled"=>true,
 "mtu"=>1450,
 :id=>"9bd99e12-499e-4f66-80c8-3239d03849bc",
 :provider_segmentation_id=>1087}
```

fog-core 2.1.2:
Different behavior of object.all_associations_and_attributes in line:
https://github.com/fog/fog-core/blob/master/lib/fog/core/model.rb#L51
Fails because underneath in line:
https://github.com/fog/fog-core/blob/master/lib/fog/core/attributes.rb#L86
Attribute :subnets triggers a "GET http://devstack.openstack.stack:9696/v2.0/subnets"

**Comment by plribeiro3000** [comment]
I believe the main issue here is that you defined `subnets` as an attribute but it is actually an association.
I've faced this problem in the past where i needed to load the association but Fog's DSL could not help on that so we had to overwrite the setter os the getter or both.
To fix it i've introduced the concept of `associations` in Fog.

I believe an easy fix for you here would be to remove the `attribute` definition and leave only the getter method since it does use only the network identifier to load its subnets.

If thats not a possibility i think you will have to go the harder way and start using Fog's association DSL. I say it might be harder because it is rather simple and might not support all your scenarios so we might have to work on top of the associations in the beginning. =)

**Comment by gildub** [comment]
@plribeiro3000, I wish I was the one who wrote that ;)

Seriously, I'm happy to remove the getter attribute. The associations sounds good but I leave that for later.

Thank you very much for you help as fog openstack is now ready to use fog-core 2+. Although there is some refactor work to be done to align properly with it and remove all the warnings/deprecation messages.

**Comment by geemus** [comment]
Thanks to both of you for continuing to work on this!
